### ISSUE TITLE
server.go logging to stdout

### ISSUE THREAD

**Issue by udhos** [icza/gowut.dev#7]
server.go has two calls to log.Println().

Shouldn't such a direct logging to stdout be prevented?

**Comment by icza** [comment]
As of 2016-11-27, development of Gowut has been moved to the `dev` branch of the gowut project: https://github.com/icza/gowut/tree/dev

Maybe, I don't know. It never bothered me, and I appreciated the logs on console. You're the first to "vote" against it.

**Comment by udhos** [comment]
Well, I am unsure as well.

Thing is, I am using server.SetLogger(fileLogger) in order to redirect my app logs to a file, but it keeps issuing "session created/removed" to console. Since those messages are correctly sent to the logger as well, I don't see it as a defect, only as an unexpected behavior.

**Comment by icza** [comment]
Maybe the correct thing would be to check if a logger is set, log only using that. If no logger set, then use `log.Println()`.

**Comment by icza** [comment]
Changed the behavior. Commit: https://github.com/icza/gowut/commit/befebd192fb2fb52bd3cd4bb90f06153bd70d445

In the future, please open issues at the gowut project.
